services:
  mongodb:
    image: mongo:7.0-jammy

    container_name: mongodb
    
    ports:
      - "27000:27017"
      
    volumes:
      - mongodata:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend
      
    restart: always

  pgvector:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend 
    restart: always

networks:
  backend:

volumes:
  mongodata:
  pgvector_data: